import { createClient } from '@supabase/supabase-js';
export function env(name){return Netlify.env.get(name)||''}
export function db(token){return createClient(env('SUPABASE_URL'),env('SUPABASE_PUBLISHABLE_KEY'),{global:{headers:{'x-edivano-token':token||''}},auth:{persistSession:false,autoRefreshToken:false}})}
export function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}})}
export function cleanText(v,max=300){return String(v??'').trim().slice(0,max)}
export function normalizeRequest(input={}){return{origin:cleanText(input.origin,80),dates:cleanText(input.dates,120),adults:Math.min(8,Math.max(1,Number(input.adults)||2)),children:cleanText(input.children,120),budget:Math.min(50000,Math.max(0,Number(input.budget)||0)),duration:cleanText(input.duration,80),preferences:Array.isArray(input.preferences)?input.preferences.slice(0,12).map(x=>cleanText(x,40)):[],notes:cleanText(input.notes,500)}}
export function fallbackDestinations(r){
  const p=r.preferences.join(', ').toLowerCase();
  const warm=p.includes('warm')||p.includes('strand');
  const all=p.includes('all inclusive');
  const base=warm?[
    {destination:'Algarve',country:'Portugal',reason:'Familienfreundliche Strände, kurze Wege und viele entspannte Ausflugsmöglichkeiten.',flight:'ca. 3,5 Std. Direktflug möglich',weather:'mild bis warm',family:'Sehr gut mit Kleinkind',accommodation:'Apartment oder Familienhotel',areas:'Lagos, Alvor oder Albufeira',priceRange:'Unterkunft oft ca. 700–1.300 € / Woche, je nach Saison',exampleDay:'Vormittags Strand, nachmittags Altstadt oder kurzer Bootsausflug.'},
    {destination:'Mallorca',country:'Spanien',reason:'Kurzer Flug, viele flache Buchten und eine riesige Auswahl an familienfreundlichen Unterkünften.',flight:'ca. 2,5 Std. Direktflug',weather:'mild bis warm',family:'Sehr einfach mit Familie',accommodation:'Familienhotel, Aparthotel oder Finca',areas:'Alcúdia, Cala d’Or oder Can Picafort',priceRange:'Unterkunft oft ca. 800–1.500 € / Woche, je nach Saison',exampleDay:'Morgens Badebucht, mittags Pause, abends Promenade oder kleiner Markt.'},
    {destination:'Kreta',country:'Griechenland',reason:'Viel Sonne, Strände und familienfreundliche Resorts mit guten Möglichkeiten für einzelne Ausflüge.',flight:'ca. 3,5 Std. Direktflug möglich',weather:'warm',family:'Gut für Badeurlaub',accommodation:all?'Familienresort / All Inclusive':'Resort, Apartment oder Hotel',areas:'Georgioupolis, Rethymno oder Chersonissos',priceRange:'Unterkunft oft ca. 850–1.600 € / Woche, je nach Saison',exampleDay:'Pool oder Strand am Vormittag, später kleiner Ortsbummel oder kurzer Familienausflug.'}
  ]:[
    {destination:'Südtirol',country:'Italien',reason:'Natur, kurze Tagesausflüge und viele familienfreundliche Unterkünfte in kompakter Region.',flight:'ca. 2 Std. Flug + Transfer oder Auto',weather:'saisonal',family:'Gut für Natur & Ruhe',accommodation:'Ferienwohnung oder Familienhotel',areas:'Meran, Seis oder Pustertal',priceRange:'Unterkunft oft ca. 700–1.400 € / Woche',exampleDay:'Leichte Wanderung oder Bergbahn, danach Spielplatz und frühes Abendessen.'},
    {destination:'Dänische Nordsee',country:'Dänemark',reason:'Entspannt, familienfreundlich und ideal für Ferienhausurlaub mit wenig Programmstress.',flight:'Anreise meist per Auto',weather:'wechselhaft',family:'Sehr entspannt mit Kind',accommodation:'Ferienhaus',areas:'Blåvand, Henne Strand oder Søndervig',priceRange:'Ferienhaus oft ca. 600–1.200 € / Woche',exampleDay:'Strandspaziergang, Mittagspause im Haus, danach Spielplatz oder Aquarium.'},
    {destination:'Salzburger Land',country:'Österreich',reason:'Natur, Seen und familienfreundliche Ausflüge mit kurzen Wegen zwischen den Highlights.',flight:'ca. 1,5 Std. Flug + Transfer oder Auto',weather:'saisonal',family:'Gut für aktive Familien',accommodation:'Appartement oder Familienhotel',areas:'Zell am See, Flachau oder Saalbach',priceRange:'Unterkunft oft ca. 750–1.400 € / Woche',exampleDay:'Vormittags See oder Bergbahn, nachmittags Tierpark oder Indoor-Alternative.'}
  ];
  return base.map(x=>({...x,budget:r.budget?'Mit ca. '+Math.round(r.budget/100)*100+' € Gesamtbudget grundsätzlich planbar':'Budget abhängig von Saison'}))
}
export function fallbackPlan(r,preview){const dest=preview?.[0]?.destination||'eurem Reiseziel';const days=Array.from({length:Math.max(4,Math.min(10,parseInt(r.duration)||7))},(_,i)=>({day:i+1,title:i===0?'Ankommen & orientieren':i===1?'Familientag mit leichtem Programm':i===2?'Ausflugstag':i===3?'Freier Vormittag & Lieblingsort':'Flexibler Familientag',plan:i===0?`Ruhig ankommen, Unterkunft beziehen und einen kurzen Spaziergang in ${dest} machen.`:i%3===0?'Vormittags entspannt starten, nachmittags eine wetterunabhängige Aktivität einplanen.':'Eine Hauptaktivität am Vormittag, danach bewusst freie Zeit und frühes Abendessen.'}));return{title:`Euer Edivano-Plan für ${dest}`,intro:`Ausgelegt auf ${r.adults} Erwachsene${r.children?` und ${r.children}`:''}, ${r.duration} und ein Gesamtbudget von ungefähr ${r.budget||'flexiblem'} Euro.`,days,activities:['Familienfreundlicher Strand- oder Naturtag','Kurzer lokaler Ausflug ohne langen Transfer','Spielplatz, Promenade oder Altstadt in kinderfreundlichem Tempo','Ein bewusst programmfreier halber Tag'],packing:['Reisedokumente und Buchungsunterlagen','Sonnen- und Regenschutz passend zur Saison','Kleine Reiseapotheke','Snacks, Trinkflasche und Beschäftigung für Transferzeiten','Kindgerechte Schlaf- und Lieblingssachen'],budget:'Plant Unterkunft und Anreise zuerst, reserviert danach ungefähr 15–25 % für Essen, Mobilität und Aktivitäten sowie einen kleinen Puffer. Prüft aktuelle Preise direkt bei den jeweiligen Anbietern.',rainy:['Aquarium, Museum oder Indoor-Spielbereich','Gemütlicher Café-/Restaurantbesuch mit kurzer Innenstadt-Runde','Wellness-/Poolzeit in der Unterkunft oder Tagesbad','Plan tauschen: Schlechtwettertag als Ruhetag nutzen']}}
